export const STATUS_AGENDAMENTO = {
  AGENDADO: 1,
  EM_ANDAMENTO: 2,
  REALIZADO: 3,
  CANCELADO: 4,
  REAGENDADO: 5
};

export const STATUS_COLORS = {
  [STATUS_AGENDAMENTO.AGENDADO]: '#3182ce', // blue.500
  [STATUS_AGENDAMENTO.EM_ANDAMENTO]: '#00b5d8', // cyan.500
  [STATUS_AGENDAMENTO.REALIZADO]: '#38a169', // green.500
  [STATUS_AGENDAMENTO.CANCELADO]: '#e53e3e', // red.500
  [STATUS_AGENDAMENTO.REAGENDADO]: '#718096' // gray.500
};

export const STATUS_LABELS = {
  [STATUS_AGENDAMENTO.AGENDADO]: 'AGENDADO',
  [STATUS_AGENDAMENTO.EM_ANDAMENTO]: 'EM ANDAMENTO',
  [STATUS_AGENDAMENTO.REALIZADO]: 'REALIZADO',
  [STATUS_AGENDAMENTO.CANCELADO]: 'CANCELADO',
  [STATUS_AGENDAMENTO.REAGENDADO]: 'REAGENDADO'
};