"""Initial schema

Revision ID: eda5680455ab
Revises: 
Create Date: 2026-05-30 10:28:41.276460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eda5680455ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macros_profissionais_id'), table_name='macros_profissionais')
    op.drop_table('macros_profissionais')
    op.alter_column('agendamentos', 'data_horario',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('agendamentos', 'status',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='1 = Agendado, 2 = Em Andamento, 3 = Realizado, 4 = Cancelado, 5 = Reagendado',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    op.drop_constraint(op.f('agendamentos_clinic_id_fkey'), 'agendamentos', type_='foreignkey')
    op.drop_constraint(op.f('agendamentos_patient_id_fkey'), 'agendamentos', type_='foreignkey')
    op.drop_constraint(op.f('agendamentos_doctor_id_fkey'), 'agendamentos', type_='foreignkey')
    op.create_foreign_key(None, 'agendamentos', 'pacientes', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'agendamentos', 'profissionais', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'agendamentos', 'clinicas', ['clinic_id'], ['id'])
    op.create_index(op.f('ix_arquivos_pacientes_id'), 'arquivos_pacientes', ['id'], unique=False)
    op.drop_constraint(op.f('arquivos_pacientes_patient_id_fkey'), 'arquivos_pacientes', type_='foreignkey')
    op.drop_constraint(op.f('arquivos_pacientes_document_id_fkey'), 'arquivos_pacientes', type_='foreignkey')
    op.drop_constraint(op.f('arquivos_pacientes_clinic_id_fkey'), 'arquivos_pacientes', type_='foreignkey')
    op.create_foreign_key(None, 'arquivos_pacientes', 'pacientes', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'arquivos_pacientes', 'clinicas', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'arquivos_pacientes', 'documentos', ['document_id'], ['id'])
    op.create_index(op.f('ix_assinaturas_id'), 'assinaturas', ['id'], unique=False)
    op.drop_constraint(op.f('assinaturas_clinic_id_fkey'), 'assinaturas', type_='foreignkey')
    op.drop_constraint(op.f('assinaturas_plan_id_fkey'), 'assinaturas', type_='foreignkey')
    op.create_foreign_key(None, 'assinaturas', 'clinicas', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'assinaturas', 'planos', ['plan_id'], ['id'])
    op.drop_constraint(op.f('cargos_nome_key'), 'cargos', type_='unique')
    op.create_index(op.f('ix_cargos_id'), 'cargos', ['id'], unique=False)
    op.create_index(op.f('ix_cargos_nome'), 'cargos', ['nome'], unique=True)
    op.create_index(op.f('ix_cargos_usuarios_id'), 'cargos_usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_cargos_usuarios_role_id'), 'cargos_usuarios', ['role_id'], unique=False)
    op.create_index(op.f('ix_cargos_usuarios_user_id'), 'cargos_usuarios', ['user_id'], unique=False)
    op.drop_constraint(op.f('cargos_usuarios_role_id_fkey'), 'cargos_usuarios', type_='foreignkey')
    op.drop_constraint(op.f('cargos_usuarios_user_id_fkey'), 'cargos_usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'cargos_usuarios', 'usuarios', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cargos_usuarios', 'cargos', ['role_id'], ['id'])
    op.drop_constraint(op.f('cids_codigo_key'), 'cids', type_='unique')
    op.create_index(op.f('ix_cids_codigo'), 'cids', ['codigo'], unique=True)
    op.create_index(op.f('ix_cids_descricao'), 'cids', ['descricao'], unique=False)
    op.create_index(op.f('ix_cids_id'), 'cids', ['id'], unique=False)
    op.drop_constraint(op.f('clinicas_cnpj_key'), 'clinicas', type_='unique')
    op.drop_constraint(op.f('clinicas_email_key'), 'clinicas', type_='unique')
    op.create_index(op.f('ix_clinicas_cnpj'), 'clinicas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_clinicas_email'), 'clinicas', ['email'], unique=True)
    op.create_index(op.f('ix_clinicas_id'), 'clinicas', ['id'], unique=False)
    op.drop_constraint(op.f('clinicas_plano_id_fkey'), 'clinicas', type_='foreignkey')
    op.create_foreign_key(None, 'clinicas', 'planos', ['plano_id'], ['id'])
    op.create_index(op.f('ix_comissoes_profissionais_id'), 'comissoes_profissionais', ['id'], unique=False)
    op.drop_constraint(op.f('comissoes_profissionais_doctor_id_fkey'), 'comissoes_profissionais', type_='foreignkey')
    op.drop_constraint(op.f('comissoes_profissionais_transaction_id_fkey'), 'comissoes_profissionais', type_='foreignkey')
    op.drop_constraint(op.f('comissoes_profissionais_appointment_id_fkey'), 'comissoes_profissionais', type_='foreignkey')
    op.create_foreign_key(None, 'comissoes_profissionais', 'profissionais', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'comissoes_profissionais', 'transacoes', ['transaction_id'], ['id'])
    op.create_foreign_key(None, 'comissoes_profissionais', 'agendamentos', ['appointment_id'], ['id'])
    op.create_index(op.f('ix_comunicacoes_id'), 'comunicacoes', ['id'], unique=False)
    op.drop_constraint(op.f('comunicacoes_clinic_id_fkey'), 'comunicacoes', type_='foreignkey')
    op.drop_constraint(op.f('comunicacoes_patient_id_fkey'), 'comunicacoes', type_='foreignkey')
    op.create_foreign_key(None, 'comunicacoes', 'pacientes', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'comunicacoes', 'clinicas', ['clinic_id'], ['id'])
    op.create_index(op.f('ix_convenios_id'), 'convenios', ['id'], unique=False)
    op.drop_constraint(op.f('convenios_clinic_id_fkey'), 'convenios', type_='foreignkey')
    op.create_foreign_key(None, 'convenios', 'clinicas', ['clinic_id'], ['id'])
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.drop_constraint(op.f('documentos_clinic_id_fkey'), 'documentos', type_='foreignkey')
    op.drop_constraint(op.f('documentos_patient_id_fkey'), 'documentos', type_='foreignkey')
    op.create_foreign_key(None, 'documentos', 'clinicas', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'documentos', 'pacientes', ['patient_id'], ['id'])
    op.create_index(op.f('ix_logs_auditoria_id'), 'logs_auditoria', ['id'], unique=False)
    op.drop_constraint(op.f('logs_auditoria_clinic_id_fkey'), 'logs_auditoria', type_='foreignkey')
    op.drop_constraint(op.f('logs_auditoria_user_id_fkey'), 'logs_auditoria', type_='foreignkey')
    op.create_foreign_key(None, 'logs_auditoria', 'usuarios', ['user_id'], ['id'])
    op.create_foreign_key(None, 'logs_auditoria', 'clinicas', ['clinic_id'], ['id'])
    op.create_index(op.f('ix_macros_id'), 'macros', ['id'], unique=False)
    op.drop_constraint(op.f('macros_doctor_id_fkey'), 'macros', type_='foreignkey')
    op.create_foreign_key(None, 'macros', 'profissionais', ['doctor_id'], ['id'])
    op.create_index(op.f('ix_pacientes_cpf'), 'pacientes', ['cpf'], unique=False)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.drop_constraint(op.f('pacientes_clinic_id_fkey'), 'pacientes', type_='foreignkey')
    op.drop_constraint(op.f('pacientes_insurance_id_fkey'), 'pacientes', type_='foreignkey')
    op.drop_constraint(op.f('pacientes_user_id_fkey'), 'pacientes', type_='foreignkey')
    op.create_foreign_key(None, 'pacientes', 'convenios', ['insurance_id'], ['id'])
    op.create_foreign_key(None, 'pacientes', 'usuarios', ['user_id'], ['id'])
    op.create_foreign_key(None, 'pacientes', 'clinicas', ['clinic_id'], ['id'])
    op.create_index(op.f('ix_planos_id'), 'planos', ['id'], unique=False)
    op.create_index(op.f('ix_precos_procedimentos_id'), 'precos_procedimentos', ['id'], unique=False)
    op.drop_constraint(op.f('precos_procedimentos_insurance_id_fkey'), 'precos_procedimentos', type_='foreignkey')
    op.drop_constraint(op.f('precos_procedimentos_clinic_id_fkey'), 'precos_procedimentos', type_='foreignkey')
    op.create_foreign_key(None, 'precos_procedimentos', 'clinicas', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'precos_procedimentos', 'convenios', ['insurance_id'], ['id'])
    op.alter_column('profissionais', 'agenda_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_profissionais_id'), 'profissionais', ['id'], unique=False)
    op.drop_constraint(op.f('profissionais_clinic_id_fkey'), 'profissionais', type_='foreignkey')
    op.drop_constraint(op.f('profissionais_user_id_fkey'), 'profissionais', type_='foreignkey')
    op.create_foreign_key(None, 'profissionais', 'usuarios', ['user_id'], ['id'])
    op.create_foreign_key(None, 'profissionais', 'clinicas', ['clinic_id'], ['id'])
    op.alter_column('prontuarios', 'specialty_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_prontuarios_id'), 'prontuarios', ['id'], unique=False)
    op.drop_constraint(op.f('prontuarios_appointment_id_fkey'), 'prontuarios', type_='foreignkey')
    op.drop_constraint(op.f('prontuarios_doctor_id_fkey'), 'prontuarios', type_='foreignkey')
    op.drop_constraint(op.f('prontuarios_clinic_id_fkey'), 'prontuarios', type_='foreignkey')
    op.drop_constraint(op.f('prontuarios_patient_id_fkey'), 'prontuarios', type_='foreignkey')
    op.create_foreign_key(None, 'prontuarios', 'profissionais', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'prontuarios', 'clinicas', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'prontuarios', 'pacientes', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'prontuarios', 'agendamentos', ['appointment_id'], ['id'])
    op.alter_column('regras_especialidades', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_regras_especialidades_id'), 'regras_especialidades', ['id'], unique=False)
    op.create_index(op.f('ix_regras_especialidades_specialty'), 'regras_especialidades', ['specialty'], unique=False)
    op.drop_constraint(op.f('regras_especialidades_clinic_id_fkey'), 'regras_especialidades', type_='foreignkey')
    op.create_foreign_key(None, 'regras_especialidades', 'clinicas', ['clinic_id'], ['id'])
    op.create_index(op.f('ix_transacoes_id'), 'transacoes', ['id'], unique=False)
    op.drop_constraint(op.f('transacoes_patient_id_fkey'), 'transacoes', type_='foreignkey')
    op.drop_constraint(op.f('transacoes_clinic_id_fkey'), 'transacoes', type_='foreignkey')
    op.drop_constraint(op.f('transacoes_appointment_id_fkey'), 'transacoes', type_='foreignkey')
    op.create_foreign_key(None, 'transacoes', 'clinicas', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'transacoes', 'agendamentos', ['appointment_id'], ['id'])
    op.create_foreign_key(None, 'transacoes', 'pacientes', ['patient_id'], ['id'])
    op.create_index(op.f('ix_unidades_id'), 'unidades', ['id'], unique=False)
    op.drop_constraint(op.f('unidades_clinic_id_fkey'), 'unidades', type_='foreignkey')
    op.create_foreign_key(None, 'unidades', 'clinicas', ['clinic_id'], ['id'])
    op.drop_constraint(op.f('usuarios_email_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.drop_constraint(op.f('usuarios_clinic_id_fkey'), 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'clinicas', ['clinic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_clinic_id_fkey'), 'usuarios', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_email_key'), 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'unidades', type_='foreignkey')
    op.create_foreign_key(op.f('unidades_clinic_id_fkey'), 'unidades', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_unidades_id'), table_name='unidades')
    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.create_foreign_key(op.f('transacoes_appointment_id_fkey'), 'transacoes', 'agendamentos', ['appointment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('transacoes_clinic_id_fkey'), 'transacoes', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('transacoes_patient_id_fkey'), 'transacoes', 'pacientes', ['patient_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_transacoes_id'), table_name='transacoes')
    op.drop_constraint(None, 'regras_especialidades', type_='foreignkey')
    op.create_foreign_key(op.f('regras_especialidades_clinic_id_fkey'), 'regras_especialidades', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_regras_especialidades_specialty'), table_name='regras_especialidades')
    op.drop_index(op.f('ix_regras_especialidades_id'), table_name='regras_especialidades')
    op.alter_column('regras_especialidades', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'prontuarios', type_='foreignkey')
    op.drop_constraint(None, 'prontuarios', type_='foreignkey')
    op.drop_constraint(None, 'prontuarios', type_='foreignkey')
    op.drop_constraint(None, 'prontuarios', type_='foreignkey')
    op.create_foreign_key(op.f('prontuarios_patient_id_fkey'), 'prontuarios', 'pacientes', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('prontuarios_clinic_id_fkey'), 'prontuarios', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('prontuarios_doctor_id_fkey'), 'prontuarios', 'profissionais', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('prontuarios_appointment_id_fkey'), 'prontuarios', 'agendamentos', ['appointment_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_prontuarios_id'), table_name='prontuarios')
    op.alter_column('prontuarios', 'specialty_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'profissionais', type_='foreignkey')
    op.drop_constraint(None, 'profissionais', type_='foreignkey')
    op.create_foreign_key(op.f('profissionais_user_id_fkey'), 'profissionais', 'usuarios', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('profissionais_clinic_id_fkey'), 'profissionais', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_profissionais_id'), table_name='profissionais')
    op.alter_column('profissionais', 'agenda_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'precos_procedimentos', type_='foreignkey')
    op.drop_constraint(None, 'precos_procedimentos', type_='foreignkey')
    op.create_foreign_key(op.f('precos_procedimentos_clinic_id_fkey'), 'precos_procedimentos', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('precos_procedimentos_insurance_id_fkey'), 'precos_procedimentos', 'convenios', ['insurance_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_precos_procedimentos_id'), table_name='precos_procedimentos')
    op.drop_index(op.f('ix_planos_id'), table_name='planos')
    op.drop_constraint(None, 'pacientes', type_='foreignkey')
    op.drop_constraint(None, 'pacientes', type_='foreignkey')
    op.drop_constraint(None, 'pacientes', type_='foreignkey')
    op.create_foreign_key(op.f('pacientes_user_id_fkey'), 'pacientes', 'usuarios', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('pacientes_insurance_id_fkey'), 'pacientes', 'convenios', ['insurance_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('pacientes_clinic_id_fkey'), 'pacientes', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_cpf'), table_name='pacientes')
    op.drop_constraint(None, 'macros', type_='foreignkey')
    op.create_foreign_key(op.f('macros_doctor_id_fkey'), 'macros', 'profissionais', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_macros_id'), table_name='macros')
    op.drop_constraint(None, 'logs_auditoria', type_='foreignkey')
    op.drop_constraint(None, 'logs_auditoria', type_='foreignkey')
    op.create_foreign_key(op.f('logs_auditoria_user_id_fkey'), 'logs_auditoria', 'usuarios', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('logs_auditoria_clinic_id_fkey'), 'logs_auditoria', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_logs_auditoria_id'), table_name='logs_auditoria')
    op.drop_constraint(None, 'documentos', type_='foreignkey')
    op.drop_constraint(None, 'documentos', type_='foreignkey')
    op.create_foreign_key(op.f('documentos_patient_id_fkey'), 'documentos', 'pacientes', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('documentos_clinic_id_fkey'), 'documentos', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_constraint(None, 'convenios', type_='foreignkey')
    op.create_foreign_key(op.f('convenios_clinic_id_fkey'), 'convenios', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_convenios_id'), table_name='convenios')
    op.drop_constraint(None, 'comunicacoes', type_='foreignkey')
    op.drop_constraint(None, 'comunicacoes', type_='foreignkey')
    op.create_foreign_key(op.f('comunicacoes_patient_id_fkey'), 'comunicacoes', 'pacientes', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('comunicacoes_clinic_id_fkey'), 'comunicacoes', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comunicacoes_id'), table_name='comunicacoes')
    op.drop_constraint(None, 'comissoes_profissionais', type_='foreignkey')
    op.drop_constraint(None, 'comissoes_profissionais', type_='foreignkey')
    op.drop_constraint(None, 'comissoes_profissionais', type_='foreignkey')
    op.create_foreign_key(op.f('comissoes_profissionais_appointment_id_fkey'), 'comissoes_profissionais', 'agendamentos', ['appointment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('comissoes_profissionais_transaction_id_fkey'), 'comissoes_profissionais', 'transacoes', ['transaction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('comissoes_profissionais_doctor_id_fkey'), 'comissoes_profissionais', 'profissionais', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comissoes_profissionais_id'), table_name='comissoes_profissionais')
    op.drop_constraint(None, 'clinicas', type_='foreignkey')
    op.create_foreign_key(op.f('clinicas_plano_id_fkey'), 'clinicas', 'planos', ['plano_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_clinicas_id'), table_name='clinicas')
    op.drop_index(op.f('ix_clinicas_email'), table_name='clinicas')
    op.drop_index(op.f('ix_clinicas_cnpj'), table_name='clinicas')
    op.create_unique_constraint(op.f('clinicas_email_key'), 'clinicas', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('clinicas_cnpj_key'), 'clinicas', ['cnpj'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cids_id'), table_name='cids')
    op.drop_index(op.f('ix_cids_descricao'), table_name='cids')
    op.drop_index(op.f('ix_cids_codigo'), table_name='cids')
    op.create_unique_constraint(op.f('cids_codigo_key'), 'cids', ['codigo'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'cargos_usuarios', type_='foreignkey')
    op.drop_constraint(None, 'cargos_usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('cargos_usuarios_user_id_fkey'), 'cargos_usuarios', 'usuarios', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('cargos_usuarios_role_id_fkey'), 'cargos_usuarios', 'cargos', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cargos_usuarios_user_id'), table_name='cargos_usuarios')
    op.drop_index(op.f('ix_cargos_usuarios_role_id'), table_name='cargos_usuarios')
    op.drop_index(op.f('ix_cargos_usuarios_id'), table_name='cargos_usuarios')
    op.drop_index(op.f('ix_cargos_nome'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_id'), table_name='cargos')
    op.create_unique_constraint(op.f('cargos_nome_key'), 'cargos', ['nome'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'assinaturas', type_='foreignkey')
    op.drop_constraint(None, 'assinaturas', type_='foreignkey')
    op.create_foreign_key(op.f('assinaturas_plan_id_fkey'), 'assinaturas', 'planos', ['plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('assinaturas_clinic_id_fkey'), 'assinaturas', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_assinaturas_id'), table_name='assinaturas')
    op.drop_constraint(None, 'arquivos_pacientes', type_='foreignkey')
    op.drop_constraint(None, 'arquivos_pacientes', type_='foreignkey')
    op.drop_constraint(None, 'arquivos_pacientes', type_='foreignkey')
    op.create_foreign_key(op.f('arquivos_pacientes_clinic_id_fkey'), 'arquivos_pacientes', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('arquivos_pacientes_document_id_fkey'), 'arquivos_pacientes', 'documentos', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('arquivos_pacientes_patient_id_fkey'), 'arquivos_pacientes', 'pacientes', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_arquivos_pacientes_id'), table_name='arquivos_pacientes')
    op.drop_constraint(None, 'agendamentos', type_='foreignkey')
    op.drop_constraint(None, 'agendamentos', type_='foreignkey')
    op.drop_constraint(None, 'agendamentos', type_='foreignkey')
    op.create_foreign_key(op.f('agendamentos_doctor_id_fkey'), 'agendamentos', 'profissionais', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('agendamentos_patient_id_fkey'), 'agendamentos', 'pacientes', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('agendamentos_clinic_id_fkey'), 'agendamentos', 'clinicas', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.alter_column('agendamentos', 'status',
               existing_type=sa.INTEGER(),
               comment='1 = Agendado, 2 = Em Andamento, 3 = Realizado, 4 = Cancelado, 5 = Reagendado',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('agendamentos', 'data_horario',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_table('macros_profissionais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('texto_padrao', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['profissionais.id'], name=op.f('macros_profissionais_doctor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('macros_profissionais_pkey'))
    )
    op.create_index(op.f('ix_macros_profissionais_id'), 'macros_profissionais', ['id'], unique=False)
    # ### end Alembic commands ###
